use crate::commands::pipelines::{load_store, save_store, Pipeline};
use crate::paths;
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};

fn schedules_dir() -> PathBuf {
    paths::claude_home().join("glyphic-schedules")
}

fn logs_dir(pipeline_id: &str) -> PathBuf {
    schedules_dir().join("logs").join(pipeline_id)
}

fn script_path(pipeline_id: &str) -> PathBuf {
    schedules_dir().join(format!("{pipeline_id}.sh"))
}

fn plist_path(pipeline_id: &str) -> PathBuf {
    dirs::home_dir()
        .expect("home dir")
        .join("Library/LaunchAgents")
        .join(format!("com.caio.glyphic.pipeline.{pipeline_id}.plist"))
}

/// Build a shell script that executes the pipeline nodes in topological order.
fn generate_script(pipeline: &Pipeline) -> String {
    let sorted = super::pipelines::topo_sort(&pipeline.nodes, &pipeline.connections);
    let log_dir = logs_dir(&pipeline.id);
    let claude_bin = paths::claude_bin();

    let mut lines = vec![
        "#!/bin/bash".to_string(),
        "set -euo pipefail".to_string(),
        format!("# Auto-generated by Glyphic for pipeline: {}", pipeline.name),
        format!("LOG_DIR=\"{}\"", log_dir.display()),
        "mkdir -p \"$LOG_DIR\"".to_string(),
        "LOG_FILE=\"$LOG_DIR/$(date +%Y%m%d-%H%M%S).log\"".to_string(),
        "exec > >(tee -a \"$LOG_FILE\") 2>&1".to_string(),
        format!("echo \"=== Pipeline: {} ===\"", pipeline.name),
        "echo \"Started: $(date)\"".to_string(),
        "echo \"\"".to_string(),
        "PREV_OUTPUT=\"\"".to_string(),
    ];

    // Declare an associative array for all node outputs
    lines.push("declare -A NODE_OUTPUTS".to_string());

    for node_id in &sorted {
        let node = match pipeline.nodes.iter().find(|n| n.id == *node_id) {
            Some(n) => n,
            None => continue,
        };

        if node.node_type == "input" || node.node_type == "output" {
            continue;
        }

        lines.push(format!("\necho \"--- {} ({}) ---\"", node.label, node.node_type));

        match node.node_type.as_str() {
            "bash" | "github" => {
                let cmd = node.config.get("command").and_then(|c| c.as_str()).unwrap_or("echo 'no command'");
                // Simple variable substitution in shell
                lines.push(format!("CMD={}", shell_quote(cmd)));
                lines.push("CMD=$(echo \"$CMD\" | sed \"s/{{{{input}}}}/$PREV_OUTPUT/g\")".to_string());
                lines.push("RESULT=$(eval \"$CMD\" 2>&1)".to_string());
                lines.push("echo \"$RESULT\"".to_string());
                lines.push("PREV_OUTPUT=\"$RESULT\"".to_string());
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$RESULT\"", node.label));
            }
            "claude" => {
                let prompt = node.config.get("prompt").and_then(|p| p.as_str()).unwrap_or("hello");
                lines.push(format!("PROMPT={}", shell_quote(prompt)));
                lines.push("if [ -n \"$PREV_OUTPUT\" ]; then".to_string());
                lines.push("  FULL_PROMPT=$(printf \"Context:\\n%s\\n\\n%s\" \"${PREV_OUTPUT:0:2000}\" \"$PROMPT\")".to_string());
                lines.push("else".to_string());
                lines.push("  FULL_PROMPT=\"$PROMPT\"".to_string());
                lines.push("fi".to_string());
                lines.push(format!("RESULT=$({} --print \"$FULL_PROMPT\" 2>&1)", claude_bin));
                lines.push("echo \"$RESULT\"".to_string());
                lines.push("PREV_OUTPUT=\"$RESULT\"".to_string());
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$RESULT\"", node.label));
            }
            "http" => {
                let url = node.config.get("url").and_then(|u| u.as_str()).unwrap_or("");
                let method = node.config.get("method").and_then(|m| m.as_str()).unwrap_or("GET");
                let body = node.config.get("body").and_then(|b| b.as_str()).unwrap_or("");

                let mut curl_args = format!("curl -s -X {method}");

                // Parse headers
                if let Some(headers_str) = node.config.get("headers").and_then(|h| h.as_str()) {
                    if let Ok(headers) = serde_json::from_str::<Vec<serde_json::Value>>(headers_str) {
                        for h in headers {
                            let key = h.get("key").and_then(|k| k.as_str()).unwrap_or("");
                            let val = h.get("value").and_then(|v| v.as_str()).unwrap_or("");
                            if !key.is_empty() {
                                curl_args.push_str(&format!(" -H {}", shell_quote(&format!("{key}: {val}"))));
                            }
                        }
                    }
                }

                if !body.is_empty() && method != "GET" && method != "HEAD" {
                    curl_args.push_str(&format!(" -d {}", shell_quote(body)));
                }
                if method == "HEAD" {
                    curl_args.push_str(" -I");
                }
                curl_args.push_str(&format!(" {}", shell_quote(url)));

                lines.push(format!("RESULT=$({curl_args} 2>&1)"));
                lines.push("echo \"$RESULT\"".to_string());
                lines.push("PREV_OUTPUT=\"$RESULT\"".to_string());
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$RESULT\"", node.label));
            }
            "transform" => {
                let op = node.config.get("operation").and_then(|o| o.as_str()).unwrap_or("passthrough");
                let transform_cmd = match op {
                    "uppercase" => "echo \"$PREV_OUTPUT\" | tr '[:lower:]' '[:upper:]'",
                    "lowercase" => "echo \"$PREV_OUTPUT\" | tr '[:upper:]' '[:lower:]'",
                    "trim" => "echo \"$PREV_OUTPUT\" | xargs",
                    "line_count" => "echo \"$PREV_OUTPUT\" | wc -l | xargs",
                    "word_count" => "echo \"$PREV_OUTPUT\" | wc -w | xargs",
                    "first_line" => "echo \"$PREV_OUTPUT\" | head -1",
                    "json_pretty" => "echo \"$PREV_OUTPUT\" | python3 -m json.tool 2>/dev/null || echo \"$PREV_OUTPUT\"",
                    _ => "echo \"$PREV_OUTPUT\"",
                };
                lines.push(format!("RESULT=$({transform_cmd})"));
                lines.push("echo \"$RESULT\"".to_string());
                lines.push("PREV_OUTPUT=\"$RESULT\"".to_string());
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$RESULT\"", node.label));
            }
            "delay" => {
                let secs = node.config.get("seconds").and_then(|s| s.as_str()).unwrap_or("1");
                lines.push(format!("sleep {secs}"));
            }
            "git" => {
                let path = node.config.get("path").and_then(|p| p.as_str()).unwrap_or(".");
                let operation = node.config.get("operation").and_then(|o| o.as_str()).unwrap_or("status");
                let branch = node.config.get("branch").and_then(|b| b.as_str()).unwrap_or("");
                let message = node.config.get("message").and_then(|m| m.as_str()).unwrap_or("");
                let git_cmd = match operation {
                    "commit" => format!("git -C {} commit -am {}", shell_quote(path), shell_quote(message)),
                    "checkout" => format!("git -C {} checkout {}", shell_quote(path), branch),
                    "clone" => format!("git clone {} {}", shell_quote(branch), shell_quote(path)),
                    "log" => format!("git -C {} log --oneline -20", shell_quote(path)),
                    _ => format!("git -C {} {}", shell_quote(path), operation),
                };
                lines.push(format!("RESULT=$({git_cmd} 2>&1)"));
                lines.push("echo \"$RESULT\"".to_string());
                lines.push("PREV_OUTPUT=\"$RESULT\"".to_string());
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$RESULT\"", node.label));
            }
            "filter" => {
                let condition = node.config.get("condition").and_then(|c| c.as_str()).unwrap_or("not_empty");
                let value = node.config.get("value").and_then(|v| v.as_str()).unwrap_or("");
                let check = match condition {
                    "not_empty" => "[ -n \"$PREV_OUTPUT\" ]".to_string(),
                    "empty" => "[ -z \"$PREV_OUTPUT\" ]".to_string(),
                    "contains" => format!("echo \"$PREV_OUTPUT\" | grep -qF {}", shell_quote(value)),
                    "not_contains" => format!("! echo \"$PREV_OUTPUT\" | grep -qF {}", shell_quote(value)),
                    "equals" => format!("[ \"$PREV_OUTPUT\" = {} ]", shell_quote(value)),
                    "not_equals" => format!("[ \"$PREV_OUTPUT\" != {} ]", shell_quote(value)),
                    "regex" => format!("echo \"$PREV_OUTPUT\" | grep -qE {}", shell_quote(value)),
                    _ => "true".to_string(),
                };
                lines.push(format!("if {check}; then"));
                lines.push("  echo \"Filter passed\"".to_string());
                lines.push("else".to_string());
                lines.push(format!("  echo \"Filter condition '{}' not met\" >&2", condition));
                lines.push("  exit 1".to_string());
                lines.push("fi".to_string());
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$PREV_OUTPUT\"", node.label));
            }
            "readfile" => {
                let path = node.config.get("path").and_then(|p| p.as_str()).unwrap_or("");
                lines.push(format!("RESULT=$(cat {} 2>&1)", shell_quote(path)));
                lines.push("echo \"$RESULT\"".to_string());
                lines.push("PREV_OUTPUT=\"$RESULT\"".to_string());
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$RESULT\"", node.label));
            }
            "writefile" => {
                let path = node.config.get("path").and_then(|p| p.as_str()).unwrap_or("");
                let mode = node.config.get("mode").and_then(|m| m.as_str()).unwrap_or("overwrite");
                if mode == "append" {
                    lines.push(format!("echo \"$PREV_OUTPUT\" >> {}", shell_quote(path)));
                } else {
                    lines.push(format!("echo \"$PREV_OUTPUT\" > {}", shell_quote(path)));
                }
                lines.push(format!("echo \"Written to {}\"", path));
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"Written to {}\"", node.label, path));
            }
            "notification" => {
                let title = node.config.get("title").and_then(|t| t.as_str()).unwrap_or("Pipeline");
                let body = node.config.get("body").and_then(|b| b.as_str()).unwrap_or("");
                let body_display = if body.is_empty() { "$PREV_OUTPUT" } else { body };
                lines.push(format!(
                    "osascript -e 'display notification \"{}\" with title \"{}\"'",
                    body_display.replace('\'', ""), title.replace('\'', "")
                ));
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$PREV_OUTPUT\"", node.label));
            }
            "jsonextract" => {
                let path = node.config.get("path").and_then(|p| p.as_str()).unwrap_or("");
                let fallback = node.config.get("fallback").and_then(|f| f.as_str()).unwrap_or("");
                // Use python3 for JSON path extraction
                lines.push(format!(
                    "RESULT=$(echo \"$PREV_OUTPUT\" | python3 -c \"import sys,json; d=json.load(sys.stdin); print(eval('d[\\'{}\\']'.replace('.','\\'][\\'')))\" 2>/dev/null || echo {})",
                    path.replace('\'', ""), shell_quote(fallback)
                ));
                lines.push("echo \"$RESULT\"".to_string());
                lines.push("PREV_OUTPUT=\"$RESULT\"".to_string());
                lines.push(format!("NODE_OUTPUTS[\"{}\"]=\"$RESULT\"", node.label));
            }
            _ => {}
        }
    }

    lines.push("\necho \"\"".to_string());
    lines.push("echo \"Completed: $(date)\"".to_string());

    lines.join("\n")
}

fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Generate a launchd plist XML for the given cron expression.
/// Supports: minute hour day-of-month month day-of-week (standard 5-field cron).
fn generate_plist(pipeline_id: &str, cron_expr: &str, script: &Path) -> String {
    let parts: Vec<&str> = cron_expr.split_whitespace().collect();
    let label = format!("com.caio.glyphic.pipeline.{pipeline_id}");

    let mut calendar_entries = String::new();

    if parts.len() == 5 {
        calendar_entries.push_str("    <key>StartCalendarInterval</key>\n    <dict>\n");

        // Minute
        if parts[0] != "*" {
            if let Ok(v) = parts[0].parse::<u32>() {
                calendar_entries.push_str(&format!("      <key>Minute</key>\n      <integer>{v}</integer>\n"));
            }
        }
        // Hour
        if parts[1] != "*" {
            if let Ok(v) = parts[1].parse::<u32>() {
                calendar_entries.push_str(&format!("      <key>Hour</key>\n      <integer>{v}</integer>\n"));
            }
        }
        // Day of month
        if parts[2] != "*" {
            if let Ok(v) = parts[2].parse::<u32>() {
                calendar_entries.push_str(&format!("      <key>Day</key>\n      <integer>{v}</integer>\n"));
            }
        }
        // Month
        if parts[3] != "*" {
            if let Ok(v) = parts[3].parse::<u32>() {
                calendar_entries.push_str(&format!("      <key>Month</key>\n      <integer>{v}</integer>\n"));
            }
        }
        // Day of week (0=Sunday)
        if parts[4] != "*" {
            if let Ok(v) = parts[4].parse::<u32>() {
                calendar_entries.push_str(&format!("      <key>Weekday</key>\n      <integer>{v}</integer>\n"));
            }
        }

        calendar_entries.push_str("    </dict>");
    } else {
        // Fallback: run every hour
        calendar_entries.push_str("    <key>StartCalendarInterval</key>\n    <dict>\n      <key>Minute</key>\n      <integer>0</integer>\n    </dict>");
    }

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{script}</string>
    </array>
{calendar_entries}
    <key>StandardOutPath</key>
    <string>{log_out}</string>
    <key>StandardErrorPath</key>
    <string>{log_err}</string>
</dict>
</plist>"#,
        script = script.display(),
        log_out = schedules_dir().join(format!("{pipeline_id}.stdout.log")).display(),
        log_err = schedules_dir().join(format!("{pipeline_id}.stderr.log")).display(),
    )
}

#[derive(Serialize)]
pub struct ScheduleLog {
    pub filename: String,
    pub timestamp: String,
    pub content: String,
}

#[tauri::command]
pub fn enable_pipeline_schedule(pipeline_id: String, cron_expr: String) -> Result<(), String> {
    let mut store = load_store();
    let pipeline = store.pipelines.iter_mut().find(|p| p.id == pipeline_id)
        .ok_or("Pipeline not found")?;

    pipeline.schedule = Some(cron_expr.clone());
    pipeline.schedule_enabled = true;

    let pipeline_clone = pipeline.clone();

    // Generate script
    let script_file = script_path(&pipeline_id);
    fs::create_dir_all(schedules_dir()).map_err(|e| format!("{e}"))?;
    fs::create_dir_all(logs_dir(&pipeline_id)).map_err(|e| format!("{e}"))?;
    let script_content = generate_script(&pipeline_clone);
    fs::write(&script_file, &script_content).map_err(|e| format!("{e}"))?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&script_file, fs::Permissions::from_mode(0o755))
            .map_err(|e| format!("{e}"))?;
    }

    // Generate and write plist
    let plist_file = plist_path(&pipeline_id);
    fs::create_dir_all(plist_file.parent().unwrap()).map_err(|e| format!("{e}"))?;
    let plist_content = generate_plist(&pipeline_id, &cron_expr, &script_file);
    fs::write(&plist_file, &plist_content).map_err(|e| format!("{e}"))?;

    // Unload first (ignore errors if not loaded)
    let _ = std::process::Command::new("launchctl")
        .args(["unload", &plist_file.to_string_lossy()])
        .output();

    // Load the plist
    let load_output = std::process::Command::new("launchctl")
        .args(["load", &plist_file.to_string_lossy()])
        .output()
        .map_err(|e| format!("launchctl load failed: {e}"))?;

    if !load_output.status.success() {
        let stderr = String::from_utf8_lossy(&load_output.stderr);
        return Err(format!("launchctl load error: {stderr}"));
    }

    save_store(&store)?;
    Ok(())
}

#[tauri::command]
pub fn disable_pipeline_schedule(pipeline_id: String) -> Result<(), String> {
    let mut store = load_store();
    if let Some(pipeline) = store.pipelines.iter_mut().find(|p| p.id == pipeline_id) {
        pipeline.schedule_enabled = false;
    }

    let plist_file = plist_path(&pipeline_id);
    if plist_file.exists() {
        let _ = std::process::Command::new("launchctl")
            .args(["unload", &plist_file.to_string_lossy()])
            .output();
        let _ = fs::remove_file(&plist_file);
    }

    let script_file = script_path(&pipeline_id);
    if script_file.exists() {
        let _ = fs::remove_file(&script_file);
    }

    save_store(&store)?;
    Ok(())
}

#[tauri::command]
pub fn list_pipeline_logs(pipeline_id: String) -> Result<Vec<ScheduleLog>, String> {
    let dir = logs_dir(&pipeline_id);
    if !dir.exists() {
        return Ok(vec![]);
    }

    let mut logs: Vec<ScheduleLog> = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(&dir)
        .map_err(|e| format!("{e}"))?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "log"))
        .collect();

    // Sort by name descending (newest first, since filenames are timestamps)
    entries.sort_by_key(|b| std::cmp::Reverse(b.file_name()));

    // Return last 20 logs
    for entry in entries.into_iter().take(20) {
        let filename = entry.file_name().to_string_lossy().to_string();
        let timestamp = filename.trim_end_matches(".log").to_string();
        let content = fs::read_to_string(entry.path())
            .unwrap_or_else(|_| "(unreadable)".to_string());
        // Limit content to 5000 chars
        let content = if content.len() > 5000 {
            format!("{}...(truncated)", &content[..5000])
        } else {
            content
        };
        logs.push(ScheduleLog { filename, timestamp, content });
    }

    Ok(logs)
}
