use crate::filter::pipeline::FilterDef;

/// Built-in filter definitions for the top 15 most common commands.
/// These are compiled into the binary — no file I/O needed at runtime.
pub static FILTERS: &[FilterDef] = &[
    // ── Git ─────────────────────────────────────────────────────────────
    FilterDef {
        name: "git_status",
        match_command: r"^git\s+status",
        strip_ansi: true,
        replace: &[],
        match_output: Some(r"(?i)nothing to commit,?\s*working\s+tree\s+clean"),
        unless: Some(r"(?i)fatal:|error:"),
        strip_lines: None,
        keep_lines: Some(
            r"(?i)^(On branch|Your branch|Changes|Untracked|modified:|new file:|deleted:|renamed:|\t|no changes)"
        ),
        truncate_lines_at: Some(120),
        head_lines: Some(30),
        tail_lines: None,
        max_lines: None,
        on_empty: Some("(clean working tree)"),
    },
    FilterDef {
        name: "git_log",
        match_command: r"^git\s+log",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)fatal:|error:"),
        strip_lines: None,
        keep_lines: Some(r"^(commit |Author:|Date:|Merge:|\s{4}\S|$)"),
        truncate_lines_at: Some(120),
        head_lines: Some(60),
        tail_lines: None,
        max_lines: None,
        on_empty: Some("(no commits)"),
    },
    FilterDef {
        name: "git_diff",
        match_command: r"^git\s+diff",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)fatal:|error:"),
        strip_lines: Some(r"^index [0-9a-f]"),
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(100),
        tail_lines: Some(10),
        max_lines: None,
        on_empty: Some("(no diff)"),
    },
    FilterDef {
        name: "git_show",
        match_command: r"^git\s+show",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)fatal:|error:"),
        strip_lines: Some(r"^index [0-9a-f]"),
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(80),
        tail_lines: Some(5),
        max_lines: None,
        on_empty: None,
    },
    // ── File listing ────────────────────────────────────────────────────
    FilterDef {
        name: "ls",
        match_command: r"^(ls|ll|la)\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: None,
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(120),
        head_lines: Some(40),
        tail_lines: Some(5),
        max_lines: None,
        on_empty: Some("(empty directory)"),
    },
    FilterDef {
        name: "tree",
        match_command: r"^tree\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: None,
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(120),
        head_lines: Some(50),
        tail_lines: Some(3),
        max_lines: None,
        on_empty: Some("(empty tree)"),
    },
    FilterDef {
        name: "find",
        match_command: r"^find\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)permission denied|error:"),
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(150),
        head_lines: Some(30),
        tail_lines: None,
        max_lines: None,
        on_empty: Some("(no results)"),
    },
    // ── Search ──────────────────────────────────────────────────────────
    FilterDef {
        name: "grep",
        match_command: r"^(grep|rg|ripgrep)\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: None,
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(30),
        tail_lines: None,
        max_lines: None,
        on_empty: Some("(no matches)"),
    },
    // ── JavaScript / Node ───────────────────────────────────────────────
    FilterDef {
        name: "npm_test",
        match_command: r"^(npm\s+test|bun\s+test|vitest|jest|npx\s+vitest|npx\s+jest)",
        strip_ansi: true,
        replace: &[
            // Strip timing noise
            (r"\s*\(\d+(\.\d+)?\s*(ms|s)\)", ""),
        ],
        match_output: None,
        unless: Some(r"(?i)FAIL|ERROR|error:|failed"),
        strip_lines: Some(r"^(\s*$|Downloading|Resolving|✓.*\d+\s*(ms|s))"),
        keep_lines: None,
        truncate_lines_at: Some(150),
        head_lines: Some(10),
        tail_lines: Some(20),
        max_lines: None,
        on_empty: Some("(all tests passed)"),
    },
    FilterDef {
        name: "npm_install",
        match_command: r"^(npm\s+install|npm\s+i\b|bun\s+install|bun\s+i\b|bun\s+add|npm\s+ci)",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)ERR!|error|WARN|warn|deprecated"),
        strip_lines: Some(r"^(\s*$|npm\s+notice|Progress:|⠙|⠹|⠸|⠼|⠴|⠦|⠧|⠇|⠏)"),
        keep_lines: None,
        truncate_lines_at: Some(120),
        head_lines: None,
        tail_lines: Some(15),
        max_lines: Some(20),
        on_empty: Some("(install completed successfully)"),
    },
    // ── Rust / Cargo ────────────────────────────────────────────────────
    FilterDef {
        name: "cargo_test",
        match_command: r"^cargo\s+test",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)FAILED|failures:|error\["),
        strip_lines: Some(r"^(\s*Compiling\s|\s*Downloading\s|\s*Fresh\s|\s*Running\s)"),
        keep_lines: None,
        truncate_lines_at: Some(150),
        head_lines: Some(10),
        tail_lines: Some(20),
        max_lines: None,
        on_empty: Some("(all tests passed)"),
    },
    FilterDef {
        name: "cargo_build",
        match_command: r"^cargo\s+(build|check|clippy)",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)error\[|warning:"),
        strip_lines: Some(r"^(\s*Compiling\s|\s*Downloading\s|\s*Fresh\s|\s*Updating\s|\s*Locking\s)"),
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: None,
        tail_lines: Some(30),
        max_lines: Some(50),
        on_empty: Some("(build succeeded)"),
    },
    // ── Network ─────────────────────────────────────────────────────────
    FilterDef {
        name: "curl",
        match_command: r"^curl\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)curl: \(\d+\)|error|failed"),
        strip_lines: Some(r"^\s*(%\s*Total|Dload|Upload|Xferd|\d+\s+\d+)"),
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(100),
        tail_lines: Some(5),
        max_lines: None,
        on_empty: None,
    },
    // ── Docker ──────────────────────────────────────────────────────────
    FilterDef {
        name: "docker_ps",
        match_command: r"^docker\s+(ps|container\s+ls)",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: None,
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(150),
        head_lines: Some(21), // header + 20 containers
        tail_lines: None,
        max_lines: None,
        on_empty: Some("(no containers)"),
    },
    // ── Cat / read (large file guard) ───────────────────────────────────
    FilterDef {
        name: "cat",
        match_command: r"^(cat|bat|less|more)\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)No such file|error:|permission denied"),
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(80),
        tail_lines: Some(10),
        max_lines: None,
        on_empty: Some("(empty file)"),
    },
    // ── Python ──────────────────────────────────────────────────────────
    FilterDef {
        name: "python_run",
        match_command: r"^(python3?|uv\s+run)\b",
        strip_ansi: true,
        replace: &[
            // Strip timing/progress noise
            (r"\s*\d+(\.\d+)?s\s*$", ""),
        ],
        match_output: None,
        unless: Some(r"(?i)Traceback|Error:|Exception:|FAILED|assert"),
        strip_lines: Some(r"^(\s*$|Downloading|Installing|Using |━+|  +━)"),
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(50),
        tail_lines: Some(20),
        max_lines: None,
        on_empty: Some("(no output)"),
    },
    FilterDef {
        name: "pip_install",
        match_command: r"^(pip3?\s+install|uv\s+(pip\s+install|add|sync))",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)ERROR:|error:|Could not|conflict"),
        strip_lines: Some(r"^(\s*$|Downloading|Using cached|━+|  +━|\s+Preparing)"),
        keep_lines: None,
        truncate_lines_at: Some(150),
        head_lines: None,
        tail_lines: Some(10),
        max_lines: Some(15),
        on_empty: Some("(install completed successfully)"),
    },
    FilterDef {
        name: "pytest",
        match_command: r"^(pytest|python3?\s+-m\s+pytest)",
        strip_ansi: true,
        replace: &[
            (r"\s*\[\s*\d+%\]", ""),
        ],
        match_output: None,
        unless: Some(r"(?i)FAILED|ERROR|ERRORS|failures"),
        strip_lines: Some(r"^(\s*$|platform |cachedir:|rootdir:|plugins:|collecting)"),
        keep_lines: None,
        truncate_lines_at: Some(150),
        head_lines: Some(10),
        tail_lines: Some(15),
        max_lines: None,
        on_empty: Some("(all tests passed)"),
    },
    // ── Go ──────────────────────────────────────────────────────────────
    FilterDef {
        name: "go_build",
        match_command: r"^go\s+(build|vet|install)",
        strip_ansi: true,
        replace: &[],
        match_output: Some(r"^\s*$"),
        unless: Some(r"(?i)error:|cannot |undefined:|imported and not used"),
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(30),
        tail_lines: Some(10),
        max_lines: Some(50),
        on_empty: Some("(build succeeded)"),
    },
    FilterDef {
        name: "go_test",
        match_command: r"^go\s+test",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)FAIL\s|--- FAIL|panic:"),
        strip_lines: Some(r"^=== RUN\s"),
        keep_lines: None,
        truncate_lines_at: Some(150),
        head_lines: Some(20),
        tail_lines: Some(20),
        max_lines: None,
        on_empty: Some("(all tests passed)"),
    },
    // ── Bun / Make / general build ──────────────────────────────────────
    FilterDef {
        name: "bun_run",
        match_command: r"^bun\s+run\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)error|Error:|ERR!|FAIL|failed|warning:"),
        strip_lines: Some(r"^(\s*$|\$\s)"),
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(40),
        tail_lines: Some(20),
        max_lines: None,
        on_empty: Some("(completed successfully)"),
    },
    FilterDef {
        name: "make",
        match_command: r"^make\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)Error \d+|error:|Stop\.|make\[.+Error"),
        strip_lines: Some(r"^make\[\d+\]: (Entering|Leaving) directory"),
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(30),
        tail_lines: Some(20),
        max_lines: Some(60),
        on_empty: Some("(build succeeded)"),
    },
    // ── Kubernetes ──────────────────────────────────────────────────────
    FilterDef {
        name: "kubectl_get",
        match_command: r"^kubectl\s+(get|describe|logs)",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)error|forbidden|not found|couldn't"),
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(60),
        tail_lines: Some(10),
        max_lines: None,
        on_empty: Some("(no resources found)"),
    },
    // ── Docker build/compose ────────────────────────────────────────────
    FilterDef {
        name: "docker_build",
        match_command: r"^docker\s+(build|compose)",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: Some(r"(?i)error|ERROR|failed to"),
        strip_lines: Some(r"^(\s*$|#\d+\s+(CACHED|DONE)|Sending build context|Step \d+/\d+ : (FROM|WORKDIR|COPY|RUN|ENV|EXPOSE|CMD|ENTRYPOINT))"),
        keep_lines: None,
        truncate_lines_at: Some(200),
        head_lines: Some(20),
        tail_lines: Some(15),
        max_lines: Some(40),
        on_empty: Some("(build succeeded)"),
    },
    // ── Wc / du / df (small output, just truncate long lines) ───────────
    FilterDef {
        name: "disk_stats",
        match_command: r"^(wc|du|df)\b",
        strip_ansi: true,
        replace: &[],
        match_output: None,
        unless: None,
        strip_lines: None,
        keep_lines: None,
        truncate_lines_at: Some(120),
        head_lines: Some(30),
        tail_lines: Some(5),
        max_lines: None,
        on_empty: None,
    },
];
