export const HOOK_EVENTS = [
  "PreToolUse",
  "PostToolUse",
  "PostToolUseFailure",
  "SessionStart",
  "SessionEnd",
  "PermissionRequest",
  "UserPromptSubmit",
  "Notification",
  "SubagentStart",
  "SubagentStop",
  "Stop",
  "StopFailure",
  "ConfigChange",
  "PreCompact",
  "PostCompact",
  "InstructionsLoaded",
  "WorktreeCreate",
  "WorktreeRemove",
  "Elicitation",
  "ElicitationResult",
  "TeammateIdle",
  "TaskCompleted",
] as const;

export type HookEvent = (typeof HOOK_EVENTS)[number];

export const HOOK_EVENT_DESCRIPTIONS: Record<HookEvent, string> = {
  PreToolUse: "Before a tool executes",
  PostToolUse: "After a tool succeeds",
  PostToolUseFailure: "After a tool fails",
  SessionStart: "When a session begins or resumes",
  SessionEnd: "When a session terminates",
  PermissionRequest: "When a permission dialog appears",
  UserPromptSubmit: "Before processing user input",
  Notification: "When notifications are sent",
  SubagentStart: "When a subagent is spawned",
  SubagentStop: "When a subagent finishes",
  Stop: "When Claude finishes responding",
  StopFailure: "When a turn ends with an API error",
  ConfigChange: "When config files change",
  PreCompact: "Before context compaction",
  PostCompact: "After context compaction",
  InstructionsLoaded: "When CLAUDE.md files load",
  WorktreeCreate: "When a worktree is created",
  WorktreeRemove: "When a worktree is removed",
  Elicitation: "When MCP requests user input",
  ElicitationResult: "When user responds to MCP",
  TeammateIdle: "When a team agent goes idle",
  TaskCompleted: "When a task is marked complete",
};
